### ISSUE TITLE
macOS install error

### ISSUE THREAD

**Issue by soupman99** [evil-mad/axidraw#102]
macOS 11.2.1
Python 3.8.2

Command:
python3 -m pip install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip

Result:

```
Collecting https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
  Downloading https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip (125kB)
     |████████████████████████████████| 133kB 2.8MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-ox6_uzki/setup.py'"'"'; __file__='"'"'/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-ox6_uzki/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-ox6_uzki/
    Complete output (56 lines):
    WARNING: Skipping axidrawinternal as it is not installed.
    Processing ./prebuilt_dependencies/axidrawinternal-2.7.0-py2.py3-none-any.whl
    Collecting future (from axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    Collecting ink-extensions>=1.1.0 (from axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/06/64/a7446c9e9856d6868b37fbd6bdb21758107c4caf35d60c918a8fcc80c22a/ink_extensions-1.1.0-py3-none-any.whl
    Collecting requests (from axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
    Collecting plotink>=1.2.2 (from axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/fe/9f/f6cc2603a1a67ffef84d9dd0571204a54a8493502eb13d6880cbda825f04/plotink-1.2.2-py3-none-any.whl
    Collecting lxml (from ink-extensions>=1.1.0->axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/db/f7/43fecb94d66959c1e23aa53d6161231dca0e93ec500224cf31b3c4073e37/lxml-4.6.2.tar.gz (3.2MB)
    Collecting urllib3<1.27,>=1.21.1 (from requests->axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/23/fc/8a49991f7905261f9ca9df5aa9b58363c3c821ce3e7f671895442b7100f2/urllib3-1.26.3-py2.py3-none-any.whl (137kB)
    Collecting idna<3,>=2.5 (from requests->axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
    Collecting certifi>=2017.4.17 (from requests->axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)
    Collecting chardet<5,>=3.0.2 (from requests->axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178kB)
    Collecting pyserial>=3.5 (from plotink>=1.2.2->axidrawinternal==2.7.0)
      Downloading https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl (90kB)
    Building wheels for collected packages: future, lxml
      Building wheel for future (setup.py): started
      Building wheel for future (setup.py): finished with status 'done'
      Created wheel for future: filename=future-0.18.2-cp38-none-any.whl size=491057 sha256=af4fa2b0eee7025dedd388ab23b9c307d8003b3d8feb7043afdb4eb0a210d03c
      Stored in directory: /Users/wally/Library/Caches/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e
      Building wheel for lxml (setup.py): started
      Building wheel for lxml (setup.py): still running...
      Building wheel for lxml (setup.py): finished with status 'done'
      Created wheel for lxml: filename=lxml-4.6.2-cp38-cp38-macosx_10_14_6_x86_64.whl size=2979029 sha256=bd3577bdc7af61967bbfa268c52312e06aeec0762367447d978323a8be454b5b
      Stored in directory: /Users/wally/Library/Caches/pip/wheels/a0/0c/b2/b0e301d586f899fdabf46a03ee9d037d2c6df30bc9efa57bae
    Successfully built future lxml
    Installing collected packages: future, lxml, ink-extensions, urllib3, idna, certifi, chardet, requests, pyserial, plotink, axidrawinternal
    ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
    Consider using the `--user` option or check the permissions.
    
    WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-ox6_uzki/setup.py", line 46, in replacement_setup
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', wheel_file])
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Library/Developer/CommandLineTools/usr/bin/python3', '-m', 'pip', 'install', 'prebuilt_dependencies/axidrawinternal-2.7.0-py2.py3-none-any.whl']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-ox6_uzki/setup.py", line 55, in <module>
        replacement_setup(
      File "/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-ox6_uzki/setup.py", line 48, in replacement_setup
        raise RuntimeError("Could not install one or more prebuilt dependencies.") from err
    RuntimeError: Could not install one or more prebuilt dependencies.
    WARNING: It looks like you might be attempting to install this in a non-pip way. This is discouraged. Use `pip install .` (or `pip install -r requirements.txt` if you are a developer with access to the relevant private repositories).
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by oskay** [comment]
The error is here:
```
    ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
```

It says that you don't have permission to install Python packages, at least in the way that you're trying to. Maybe you installed Python with sudo, for example, and it won't let you (a regular user) mess with that installation. 

This issue appears to be specific to the particular Python setup that you're using.  Consider a different method of installing Python 3 (I recommend homebrew), or (better) using a virtual environment. This allows you to create local installations of python packages, even when your main python is unwritable. 

 Here are some articles that explain how you can do so:
https://realpython.com/python-virtual-environments-a-primer/
https://help.dreamhost.com/hc/en-us/articles/115000695551-Installing-and-using-virtualenv-with-Python-3
