### ISSUE TITLE
Unable to install Python API on Pi - "g_resources.RequirementParseError: Invalid URL given"

### ISSUE THREAD

**Issue by andypiper** [evil-mad/axidraw#161]
Latest Raspberry Pi OS (Bullseye), Python 3.9

Full output

```
$ pip3 install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
  Using cached https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip (379 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 101, in __init__
    raise InvalidRequirement("Invalid URL given")
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid URL given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 346, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    self._result = resolver.resolve(
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in get_dependencies
    return [
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in <listcomp>
    return [
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 247, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3033, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid URL given
```

**Comment by andypiper** [comment]
Update, tried cloning the repo and running `pip install .` inside `axidraw/cli` and this completed without issues.

**Comment by andypiper** [comment]
Manually downloading the zip and running `pip install .` within fails in the same way as the initially-reported issue. So it seems as though something is missing between the 392 zip file and the current git HEAD.

**Comment by andypiper** [comment]
```
$ diff AxiDraw_API_392/ axidraw/cli 
Common subdirectories: AxiDraw_API_392/axicli and axidraw/cli/axicli
Only in AxiDraw_API_392/: documentation
Only in AxiDraw_API_392/: examples_config
Only in AxiDraw_API_392/: examples_py_axidraw
Only in axidraw/cli: examples_python
diff AxiDraw_API_392/Installation.txt axidraw/cli/Installation.txt
3c3
< Supported on python 3.7 and newer
---
> Supported on python 3.6 and newer
27c27
< 3.) [Recommended, optional] Use virtualenv to control versioning
---
> 3.) [Optional:] Use virtualenv to control versioning
65d64
< Most users can use this commmand:
69,75d67
<
< ```
<
< or the equivalent:
<
< ```
< python -m pip install .
76a69
> (On Windows, you may need to use "python -m pip install .")
78,80d70
< Some additional flags on pip (like `--user`) are not supported in most
< situations. If you need to customize the installation (e.g., with extra `pip`
< flags like `--user`), you should use the commands here: https://gitlab.com/evil-mad/AxiCli/bin/alt_install.
209c199
< Copyright 2021 Windell H Oskay, Evil Mad Scientist Laboratories
---
> Copyright 2020 Windell H Oskay, Evil Mad Scientist Laboratories
Only in AxiDraw_API_392/: prebuilt_dependencies
Common subdirectories: AxiDraw_API_392/pyaxidraw and axidraw/cli/pyaxidraw
diff AxiDraw_API_392/pyproject.toml axidraw/cli/pyproject.toml
45d44
< hershey = ["hersheyadvanced"] # see Installation instructions
Common subdirectories: AxiDraw_API_392/requirements and axidraw/cli/requirements
diff AxiDraw_API_392/setup.py axidraw/cli/setup.py
15c15
<         'ink_extensions>=1.3.2',
---
>         'ink_extensions>=1.2.0',
Common subdirectories: AxiDraw_API_392/test and axidraw/cli/test
pi@labserver:~ $
```

So, it looks like `hersheyadvanced` was removed from the dependencies (and indeed I cannot find that in the usual Python indexes). Apart from that, I'm not entirely sure what is tripping up the documented install process. HTH?

**Comment by oskay** [comment]
First, try `pip3 install --upgrade pip`  

If that does not improve the situation, please let me know the specific versions of the OS, python, pip.

**Comment by andypiper** [comment]
This has indeed resolved things.

```
$ pip3 install --upgrade pip

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (20.3.4)
Collecting pip
  Downloading https://www.piwheels.org/simple/pip/pip-23.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 180 kB/s
Installing collected packages: pip
Successfully installed pip-23.2
$ pip3 -V
pip 23.2 from /home/pi/.local/lib/python3.9/site-packages/pip (python 3.9)
```

[cleanup previous attempts]

```
$ pip3 install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
  Using cached https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip (379 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Processing /tmp/pip-req-build-0hwpeb_t/prebuilt_dependencies/axidrawinternal-3.9.2-py2.py3-none-any.whl (from axicli==3.9.2)
Collecting ink-extensions>=1.3.2 (from axicli==3.9.2)
  Using cached https://www.piwheels.org/simple/ink-extensions/ink_extensions-1.3.2-py3-none-any.whl (33 kB)
Collecting lxml>=4.9.1 (from axicli==3.9.2)
  Obtaining dependency information for lxml>=4.9.1 from https://files.pythonhosted.org/packages/de/07/fcfc5adfb793e6181049a361b2909723c5821b2bc18a21064da4429631a8/lxml-4.9.3-cp39-cp39-manylinux_2_28_aarch64.whl.metadata
  Downloading lxml-4.9.3-cp39-cp39-manylinux_2_28_aarch64.whl.metadata (3.8 kB)
Requirement already satisfied: plotink>=1.8.0 in ./.local/lib/python3.9/site-packages (from axicli==3.9.2) (1.8.0)
Requirement already satisfied: pyserial>=3.5 in ./.local/lib/python3.9/site-packages (from axicli==3.9.2) (3.5)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from axicli==3.9.2) (2.25.1)
Requirement already satisfied: packaging>=21.0 in ./.local/lib/python3.9/site-packages (from plotink>=1.8.0->axicli==3.9.2) (23.1)
Requirement already satisfied: future in ./.local/lib/python3.9/site-packages (from axidrawinternal@ file:///tmp/pip-req-build-0hwpeb_t/prebuilt_dependencies/axidrawinternal-3.9.2-py2.py3-none-any.whl->axicli==3.9.2) (0.18.3)
Requirement already satisfied: pyclipper>=1.1.0 in ./.local/lib/python3.9/site-packages (from axidrawinternal@ file:///tmp/pip-req-build-0hwpeb_t/prebuilt_dependencies/axidrawinternal-3.9.2-py2.py3-none-any.whl->axicli==3.9.2) (1.3.0.post4)
Requirement already satisfied: tqdm>=4.64.0 in ./.local/lib/python3.9/site-packages (from axidrawinternal@ file:///tmp/pip-req-build-0hwpeb_t/prebuilt_dependencies/axidrawinternal-3.9.2-py2.py3-none-any.whl->axicli==3.9.2) (4.65.0)
Using cached lxml-4.9.3-cp39-cp39-manylinux_2_28_aarch64.whl (7.8 MB)
Building wheels for collected packages: axicli
  Building wheel for axicli (pyproject.toml) ... done
  Created wheel for axicli: filename=axicli-3.9.2-py3-none-any.whl size=22753 sha256=47557999cd911fb6a0a47fcafbbf051976aa8b430f97b8fbaf71a16b9bf93404
  Stored in directory: /tmp/pip-ephem-wheel-cache-cwko6nhi/wheels/75/a2/cd/838084d7456d8107af8d9cb082a1a49bf5c52581c64cc2cdbe
Successfully built axicli
Installing collected packages: lxml, ink-extensions, axidrawinternal, axicli
Successfully installed axicli-3.9.2 axidrawinternal-3.9.2 ink-extensions-1.3.2 lxml-4.9.3
```

Thanks - will close this out.

**Comment by oskay** [comment]
Great; IIRC, there was an issue in pip about the traceback on `_DistInfoDistribution__dep_map` a couple of years ago. Glad the fix was straightforward.
