### ISSUE TITLE
Big Sur seems to break the drivers (via inkscape)

### ISSUE THREAD

**Issue by zoso95** [evil-mad/axidraw#97]
Hey all, 

I just updated to Big Sur the other day, and now when I try to use this through inkscape I get the attached error. It seems to be related to this https://community.platformio.org/t/macos-big-sur-dlsym-rtld-default-kiomasterportdefault-symbol-not-found/17129

Traceback (most recent call last):
  File "axidraw_control.py", line 250, in <module>
    exit_status.run(e.affect)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/ink_extensions_utils/exit_status.py", line 26, in run
    return func(*args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/ink_extensions/inkex.py", line 285, in affect
    self.effect()
  File "axidraw_control.py", line 171, in effect
    self.plot_to_axidraw(self.options.port, True)
  File "axidraw_control.py", line 232, in plot_to_axidraw
    ad.effect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw.py", line 343, in effect
    self.serial_connect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw.py", line 2809, in serial_connect
    self.serial_port = ebb_serial.openPort()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/plotink/ebb_serial.py", line 305, in openPort
    found_port = findPort()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/plotink/ebb_serial.py", line 53, in findPort
    from serial.tools.list_ports import comports
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found

**Comment by zoso95** [comment]
The python api still works though python

**Comment by oskay** [comment]
This should already be resolved in the current version.

Please reinstall the AxiDraw software, making sure that you're using the current release (270r5), and let me know if that fixes it.

**Comment by zoso95** [comment]
yup that fixed it
